version: '3.8'

services:
  cloudflare-failover:
    build:
      context: ../../
      dockerfile: examples/docker/Dockerfile
    container_name: cloudflare-intelligent-failover
    restart: unless-stopped
    environment:
      # Azure Key Vault (recommended)
      - AZURE_KEY_VAULT_URL=${AZURE_KEY_VAULT_URL:-}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID:-}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID:-}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET:-}
      # Fallback environment variables for CF credentials only
      - CF_API_TOKEN=${CF_API_TOKEN:-}
      - CF_ZONE_ID=${CF_ZONE_ID:-}
      # Optional settings
      - TTL=120
      - LOG_FILE=/var/log/intelligent_failover.log
      # Note: DOMAIN, PRIMARY_IP, and BACKUP_IP are hardcoded in the script
    volumes:
      - ./data:/app/data
      - ./logs:/var/log
    command: ["python", "intelligent_failover.py", "monitor"]
    healthcheck:
      test: ["CMD", "python", "intelligent_failover.py", "status"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge