version: '3.8'

services:
  cloudflare-failover:
    build:
      context: ../../
      dockerfile: examples/docker/Dockerfile
    container_name: cloudflare-intelligent-failover
    restart: unless-stopped
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - DOMAIN=${DOMAIN}
      - PRIMARY_IP=${PRIMARY_IP}
      - BACKUP_IP=${BACKUP_IP}
      - TTL=120
      - LOG_FILE=/var/log/intelligent_failover.log
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data:/app/data
      - ./logs:/var/log
    command: ["python", "intelligent_failover.py", "monitor"]
    healthcheck:
      test: ["CMD", "python", "intelligent_failover.py", "status"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge